#%RAML 1.0 DataType

displayName: Unauthorized
description: Unauthenticated client requested a resource that requires authentication.
type: !include error.raml
discriminator: status
discriminatorValue: unauthorized
