#%RAML 1.0 DataType

displayName: Forbidden
description: |
  Server understood the request but is refusing it.

  Could be caused by incorrect instructions or an authenticated client
  requesting a resource or action that requires permissions that the client does
  not have assigned.
type: !include error.raml
discriminatorValue: forbidden
example:
  status: forbidden
  message: the current user is not permitted to perform this action
