#%RAML 1.0 DataType

displayName: Method Not Allowed
description: |
  The HTTP method used to request a resource is not allowed or configured by the
  server.
type: !include error.raml
discriminatorValue: bad-method
example:
  status: bad-method
  message: PUT requests are not permitted on this endpoint
