#%RAML 1.0 DataType

displayName: Method Not Allowed
description: |
  The HTTP method used to request a resource is not allowed or configured by the
  server.
type: !include error.raml
discriminator: status
discriminatorValue: bad-method
