#%RAML 1.0 DataType

displayName: Unprocessable Entity
description: |
  The request payload or parameters are correctly structured but fail resource
  specific validation.
type: !include error.raml
discriminator: status
discriminatorValue: invalid-input
properties:
  errors:
    properties:
      general:
        description: Non-field specific errors.
        type: string[]
      byKey:
        description: Field specific errors
        properties:
          //: string[]
