#%RAML 1.0 Library

types:
  Error:
    type: object
    properties:
      status: ErrorType
      message: string
    discriminator: status
    additionalProperties: false

  ErrorType:
    enum:
    - 'bad-request'
    - 'unauthorized'
    - 'forbidden'
    - 'not-found'
    - 'bad-method'
    - 'conflict'
    - 'gone'
    - 'invalid-input'
    - 'server-error'

  BadRequestError:
    displayName: Bad Request
    description: Request could not be parsed or was otherwise unusable.
    type: Error
    discriminatorValue: bad-request
    example:
      status: bad-request
      message: malformed JSON

  UnauthorizedError:
    displayName: Unauthorized
    description: |
      Unauthenticated client requested a resource that requires authentication.
    type: Error
    discriminatorValue: unauthorized
    example:
      status: unauthorized
      message: users must be logged in to access this resource

  ForbiddenError:
    displayName: Forbidden
    description: |
      Server understood the request but is refusing it.

      Could be caused by incorrect instructions or an authenticated client
      requesting a resource or action that requires permissions that the client
      does not have assigned.
    type: Error
    discriminatorValue: forbidden
    example:
      status: forbidden
      message: the current user is not permitted to perform this action

  NotFoundError:
    displayName: Not Found
    description: The requested resource was not found on this server.
    type: Error
    discriminatorValue: not-found
    example:
      status: not-found
      message: the requested resource could not be found

  MethodNotAllowedError:
    displayName: Method Not Allowed
    description: |
      The HTTP method used to request a resource is not allowed or configured by
      the server.
    type: Error
    discriminatorValue: bad-method
    example:
      status: bad-method
      message: PUT requests are not permitted on this endpoint

  ConflictError:
    displayName: Conflict
    description: |
      The request could not be completed due to a conflict with the current
      state of the resource.

      If you submitted a resource, that resource may already exist.
    type: Error
    discriminatorValue: conflict
    example:
      status: conflict
      message: Target resource already exists and cannot be overwritten.

  GoneError:
    displayName: Gone
    description: |
      The request could not be completed due to the requested resource or its
      underlying data no longer being present on the server.
    type: Error
    discriminatorValue: gone
    example:
      status: gone
      message: The target resource or its dependencies no longer exists.

  UnprocessableEntityError:
    displayName: Unprocessable Entity
    description: |
      The request payload or parameters are correctly structured but fail resource
      specific validation.
    type: Error
    discriminatorValue: invalid-input
    properties:
      errors:
        properties:
          general:
            description: Non-field specific errors.
            type: string[]
          byKey:
            description: Field specific errors
            properties:
              //: string[]
    example:
      status: invalid-input
      message: JSON validation failed
      errors:
        general: []
        byKey:
          id: [ Given ID value does not point to an existing record. ]

  ServerError:
    displayName: Internal Server Error
    type: Error
    discriminatorValue: server-error
    properties:
      requestId: string
    example:
      status: server-error
      message: Datastore connection lost
      requestId: b296c3d9-4032-41b1-906e-c97ccfc447e3
